# ===================================
# APPLICATION
# ===================================
spring.application.name=e-commerce
spring.profiles.active=local

# ===================================
# DATABASE
# ===================================
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=never
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

# ===================================
# PAGEABLE
# ===================================
spring.data.web.pageable.serialization-mode=via_dto

# ===================================
# MINIO
# ===================================
minio.endpoint=${MINIO_ENDPOINT}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}
minio.bucket=products
spring.servlet.multipart.max-file-size=5242880
spring.servlet.multipart.max-request-size=26214400

# ===================================
# JWT
# ===================================
jwt.secret-key=${JWT_SECRET_KEY}
jwt.refresh-token-expiration=604800000
jwt.access-token-expiration=900000
jwt.max-refresh-token-use=1

# ===================================
# SWAGGER
# ===================================
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# ===================================
# FRONTEND
# ===================================
app.frontend-url=http://localhost:3000

# ===================================
# MAIL
# ===================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true
support.email=${SUPPORT_EMAIL}