# ===================================
# APPLICATION
# ===================================
spring.application.name=e-commerce

spring.profiles.active=local
#server.port=8080

# ===================================
# DATABASE
# ===================================
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=ecommerce
spring.datasource.password=ecommerce_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=never

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

# ===================================
# MINIO
# ===================================
minio.endpoint=http://localhost:9000
minio.access-key=admin
minio.secret-key=admin123

spring.servlet.multipart.max-file-size=5242880
spring.servlet.multipart.max-request-size=26214400

#jwt
jwt.secret-key=jV7vqVjUDx+va09oRGUbmmXqggZ3stDZ4ixgCVfuCCU=
jwt.refresh-token-expiration=604800000
jwt.access-token-expiration=900000
jwt.max-refresh-token-use=1

# SWAGGER
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

spring.security.user.name=admin
spring.security.user.password=123456

app.frontend-url=http://localhost:3000


# ===================================
# LOGGING
# ===================================
#logging.level.root=INFO
#logging.level.com.app=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
